{
    //https://www.duanju8.cc/
    "搜索":"{wd}",
    "搜索url":"https://www.duanju8.cc/search/-------------.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"短剧$1#恋爱$2#反转$3#悬疑$4#穿越$5#古装$6#都市$7#",
    "分类url":"https://www.duanju8.cc/type/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/year/{year}/page/{catePg}.html"
    //地区{area}，排序{by}，剧情{class}，分类{cateId}，语言{lang}，年份{year}，页面{catePg}
}