{
    //http://www.rzjy985.com/
    "搜索":"{wd}",
    "搜索url":"http://www.rzjy985.com/vodsearch/-------------/?wd={wd}&submit=",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"短剧$douyinduanju#电视剧$dianshiju#电影$dianying#综艺$zongyijiemu#动漫$dongman#",
    "分类url":"http://www.rzjy985.com/vodshow/{cateId}--{by}------{catePg}---{year}.html"
    //地区{area}，排序{by}，剧情{class}，分类{cateId}，语言{lang}，年份{year}，页面{catePg}
}