{
    //https://www.aibzhan.top/
    "搜索":"{wd}",
    "搜索url":"https://kanb.tv/Videosearch/KKKKKKKKKKKKK.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"哔哩$bilibili#电影$Movie#电视剧$lianxuju#综艺$Variety#",
    "分类url":"https://kanb.tv/Show/{cateId}KK{by}KKKKKK{catePg}KKK{year}.html"
    //地区{area}，排序{by}，剧情{class}，分类{cateId}，语言{lang}，年份{year}，页面{catePg}
}