{
    //https://zimu.app/
    "搜索":"{wd}",
    "搜索url":"https://zimu.app/vodsearch.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"字母$1#国产$2#剧情$3#动漫$4#伦理$36#",
    "分类url":"https://zimu.app/vodshow/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/year/{year}/page/{catePg}.html"
    //地区{area}，排序{by}，剧情{class}，分类{cateId}，语言{lang}，年份{year}，页面{catePg}
}
