{
    //https://www.appmovie.link/
    "搜索":"{wd}",
    "搜索url":"https://www.appmovie.link/index.php/vod/search.html?wd={wd}&submit=",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$1#电视剧$2#综艺$3#动漫$4#",
    "分类url":"https://www.appmovie.link/index.php/vod/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/year/{year}/page/{catePg}.html"
    //地区{area}，排序{by}，剧情{class}，分类{cateId}，语言{lang}，年份{year}，页面{catePg}
}