{
    //https://qsd.icu/
    "搜索":"{wd}",
    "搜索url":"https://www.7sd.cn/vodsearch.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$dianying#电视剧$dianshiju#综艺$zongyi#动漫$dongman#短剧$duanju#",
    "分类url":"https://www.7sd.cn/vodtype/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/year/{year}/page/{catePg}.html"
}