{
    //https://taozi007.com/
    "搜索":"{wd}",
    "搜索url":"https://taozi007.com/search/-------------.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"学英语i$0#https://weibo.com/iwcwc$1#",
    "分类url":"https://taozi007.com/{cateId}--------{catePg}---.html"
}