{
    //https://www.yyds.one/
    "搜索":"{wd}",
    "搜索url":"https://www.yyds.one/search/-------------.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$1#电视剧$2#综艺$3#动漫$4#",
    "分类url":"https://www.yyds.one/show/{cateId}-{area}-{by}-{class}-{lang}----{catePg}---{year}.html"
}