{
    //https://www.xiongmaoyingshi.com/
    "搜索":"{wd}",
    "搜索url":"https://www.xiongmaoyingshi.com/so/%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电视剧$2#电影$1#动漫$3#综艺$4#短剧$34#.$lunli#.$fuli#",
    "分类url":"https://www.xiongmaoyingshi.com/t/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/year/{year}/page/{catePg}.html"
}