{
    //https://www.kanxiwa.com/
    "搜索":"{wd}",
    "搜索url":"https://www.kanxiwa.com/search/-------------.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"学英语i$0#电影$1#电视剧$2#综艺$3#动漫$4#热门$5#",
    "分类url":"https://www.kanxiwa.com/list/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/year/{year}/page/{catePg}.html"
}