{
    //https://www.duanju001.com/
    "搜索":"{wd}",
    "搜索url":"https://www.duanju001.com/search/-------------.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"短剧$duanju#",
    "分类url":"https://www.duanju001.com/type/show/id/{cateId}.html"
    //地区{area}，排序{by}，剧情{class}，分类{cateId}，语言{lang}，年份{year}，页面{catePg}
}