{
    //https://www.gzypcny.com/
    "搜索":"{wd}",
    "搜索url":"https://www.gzypcny.com/djsearch/-------------.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$1#电视剧$2#综艺$3#动漫$4#短剧$5",
    "分类url":"https://www.gzypcny.com/djshow/{cateId}----{lang}----{catePg}---.html"
    //分类{cateId}，地区{area}，排序{by}，剧情{class}，语言{lang}，页面{catePg}，年份{year}
}