{
    //https://www.cdnkan.top/
    "搜索":"{wd}",
    "搜索url":"https://www.physkan.com/phsch.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$1#电视剧$2#综艺$3#动漫$4#短剧$7#",
    "分类url":"https://www.panghuys.com/vodshow/{cateId}/area/{area}/by/{by}/class/{class}/lang/{lang}/page/{catePg}/year/{year}.html"
}