{
    //https://www.sososo.la/
    "搜索":"{wd}",
    "搜索url":"https://www.putaojuchang.com/search.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"学英语i$1#",
    "分类url":"https://www.putaojuchang.com/show/1/page/show/page/{catePg}.html"
}