{
    //https://www.dandanju.vip/
    "搜索模式":"{wd}",
    "搜索url":"https://www.dandanju.cc/search/{wd}-------------.html",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$1#电视剧$2#综艺$3#动漫$4",
    "分类url":"https://www.dandanju.cc/show/{cateId}-{area}--{class}-----{catePg}---{year}.html"
}