{
    //https://www.80kk.app/
    "搜索":"{wd}",
    "搜索url":"https://www.6080yy3.com/vod-s/-------------.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$1#电视剧$2#综艺$3#动漫$4#纪录片$63#",
    "分类url":"https://www.6080yy3.com/vodshow/{cateId}--------{catePg}---.html"
}
