{
    //https://bzhanyy.com/
    "搜索":"{wd}",
    "搜索url":"https://bzhanyy.com/index.php/vod/search.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电视剧$2#电影$1#综艺$3#动漫$4#短剧$27#.$26",
    "分类url":"https://bzhanyy.com/index.php/vod/show/area/{area}/by/{by}/id/{cateId}/page/{catePg}/year/{year}.html"
}