{
    //https://www.suying.lol/
    "搜索":"{wd}",
    "搜索url":"https://www.suying.lol/index.php/vod/search.html?wd={wd}",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$1#电视剧$2#综艺$3#动漫$4#纪录片$5#短剧$39",
    "分类url":"https://www.suying.lol/index.php/vod/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/page/{catePg}/year/{year}.html"
}