{
    //https://www.mov8.cc/
    "搜索":"{wd}",
    "搜索url":"https://www.mov8.cc/index.php/vod/search.html?wd={wd}&submit=",
    "影片状态":"来自🇨🇳微博@学英语i",
    "影片类型":"🇨🇳微博@学英语i",
    "分类":"电影$1#电视剧$2#综艺$3#动漫$4#短剧$41#",
    "分类url":"https://www.mov8.cc/index.php/vod/type/id/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/year/{year}/page/{catePg}.html"
}